const hero = [
    {
        name: "Abbadon",
        history: "A Fonte do Averno é a origem do poder de uma família, uma rachadura em pedras primitivas da qual vapores de poderes proféticos surgiram durante gerações. Cada recém-nascido na Casa Averno é banhado na neblina negra e sob este batismo eles recebem uma conexão às energias místicas dessa terra. Eles crescem com o pensamento de que são bárbaros protetores das suas tradições e dos costumes do reino enquanto, na verdade, são os protetores da própria Fonte. Os motivos da neblina, ninguém entende. Quando a criança Abaddon foi banhada na Fonte, dizem que algo deu errado. Nos olhos da criança brilhava uma luz de compreensão que assustou todas as pessoas presentes e fez com que os sacerdotes começassem a sussurrar uns aos outros. Ele foi criado com a expectativa total de seguir o caminho de todo outro descendente do Averno; treinar a guerrear, pois para que em momentos de necessidade ele possa liderar o exército da família em defesa das terras ancestrais. Mas Abaddon estava sempre seguindo o seu próprio caminho. Enquanto outros treinavam com armas, ele inclinou-se à meditação na presença da neblina. Ele bebeu profundamente dos vapores que eram emitidos na Fonte, aprendendo a mesclar o seu espírito com o poder que fluía sob a Casa e, assim, tornou-se uma criatura da neblina negra. Mas havia conflitos na Casa Averno; idosos e jovens acusando Abaddon de estar negligenciando as suas responsabilidades. Mas tais acusações cessaram quando Abaddon cavalgou à batalha e todos viram como os poderes da neblina forneceram-lhe um domínio sobre a vida e a morte, um domínio que nenhum lorde da Casa jamais viu antes.",
        play_style: "Abaddon é um herói versátil que pode absorver dano e proteger seus aliados com escudos. Diferente de outros suportes,  Tempo Emprestado permite Abaddon ficar no meio do campo de batalha, convertendo ataques em vida.  Espiral da Neblina e  Escudo Afótico são habilidades que dificultam muito o abate de um aliado por parte de inimigos, e seus intervalos entre usos baixos podem determinar o destino de uma luta em diversos momentos.  Maldição de Averno causa retardo em inimigos que forem atingidos pela sua espada, dificultando possíveis fugas, ao mesmo tempo que amplifica tanto a velocidade de movimento quanto de ataque de Abaddon e seus aliados se eles atacarem o inimigo amaldiçoado. Embora a configuração de itens do Abaddon em sua função principal (suporte) não permita que ele causa dano o suficiente para abater inimigos por si só, ainda são fontes de dano bem favoráveis para um suporte, e, sob circunstâncias favoráveis, Abaddon pode ser jogado como semi-carregador."
    },
    {
        name: "Axe",
        history: "Mesmo quando soldado de baixa patente do Exército da Névoa Vermelha, Mogul Khan ambicionava a patente de General da Névoa Vermelha. Batalha após batalha, ele provou o seu valor através dos seus atos violentos. A sua ascensão pelas patentes foi ajudada pelo fato dele nunca hesitar em decapitar um superior. Durante os sete anos da Campanha dos Mil Lagos, destacou-se dos outros em gloriosos massacres, a sua estrela da fama brilhando cada vez mais enquanto o número de companheiros de armas minguava constantemente. Na noite da vitória suprema, o Axe declarou-se o novo General da Névoa Vermelha e tomou o título máximo de Axe. Mas os números das suas tropas haviam chegado a zero. Claro, muitos morreram em batalha, mas um número significativo também caíra pela lâmina de Axe. Desnecessário dizer, agora a maioria dos soldados evita a sua liderança. Mas isso é insignificante para Axe, que sabe que um exército de um homem só é, sem dúvida, o melhor.",
        play_style: "Um por um dos soldados da Névoa Vermelha caíram, alguns em batalha, outros pela ambição de Moghul Khan, até que o autodeclarado general se viu como um comandante sem tropas. Não importa, pensou Axe. O exército de um homem é o melhor exército de todos. Saltando para batalha, Moghul Khan força os inimigos próximos a atacá-lo com um provocante Grito do Furioso. Absorvendo golpes de todas as direções, Axe reage girando seu machado em uma Contraespiral, facilmente despachando o enxame que reuniu. Infelizmente, alguns não ficam o tempo suficiente para encontrar seu fim. Os poucos sobreviventes que mancam para longe de Moghul Khan, sentem uma inexplicável Fome de Batalha, uma fome que nunca é saciada, até Axe envia-los para uma morte prematura com a Lâmina de Abate."
    },
    {
        name: "Dragon Knight",
        history: "Após anos no rastro de um ancivorme lendário, o próprio Cavaleiro Davion viu-se enfrentando um oponente desapontador: o temido Slyrak cresceu velho e frágil. As suas asas, esfarrapadas, as suas poucas escamas que sobraram, apodrecendo, as suas presas, enfraquecidas, e o seu sopro de fogo não ameaçava nada mais do que um pacote de palitos de fósforos molhados. Vendo que não havia honra em assassinar tal criatura, o Cavaleiro Davion preparava-se para dar as costas e deixar o seu velho adversário morrer em paz. Mas uma voz rastejou nos seus pensamentos... Era Slyrak, que fazia um apelo sussurrante para que Davion honrasse-o com uma morte em combate. Davion aceitou, e viu-se ser recompensado muito além do que imaginava pelo seu ato de misericórdia: enquanto mergulhava a sua espada no peito de Slyrak, o dragão atravessava a garganta de Davion com uma garra. Enquanto os seus sangues se misturavam, Slyrak enviou o seu poder através da rota de sangue, transmitindo toda a sua força e séculos de sabedoria ao cavaleiro. A morte do dragão selou o elo entre os dois, e assim nascera o Dragon Knight. O poder ancestral adormece no Cavaleiro Dragão Davion, despertando quando é chamado. Ou talvez seja o dragão quem chama o cavaleiro...",
        play_style: "Enquanto Sir Davion matava Slyrak em combate organizado, o sangue dos Eldwurm se misturava com o seu, selando suas essências. Ele não era mais um matador de dragões, mas um cavaleiro do dragão. A infusão de Sangue de Dragão fez com que suas feridas se curassem com velocidade desumana e concedeu-lhe grandes novos poderes. Em nenhum lugar tão grandioso quanto Slyrak, ele se viu com a capacidade de Breathe Fire, imolando pacotes de inimigos de uma só vez. Mas quando Davion assumiu sua Forma de Dragão Ancião, ele se tornou o próprio Eldwurm, e contra seus inimigos impressionados, choveu projéteis de ácido, fogo e gelo."
    },
    {
        name: "Pudge",
        history: "Nos Campos da Carnificina Perpétua, ao extremo sul de Quoidge, uma figura corpulenta trabalha incessantemente noite afora – desmembrando, eviscerando, empilhando os membros e as vísceras dos derrotados para que o campo de batalha esteja limpo ao amanhecer. Nesta região amaldiçoada, nada se deteriora ou decompõe; nenhum cadáver jamais poderá regressar para a terra de onde surgiu, não importa o quão profunda seja a sepultura. Rodeado por aves carniceiras que precisam dele para cortar as suas refeições em nacos pequenos o bastante para os seus bicos, Pudge, o Butcher, um açougueiro que aperfeiçoa a sua perícia com lâminas as quais quanto mais são usadas, mais ficam afiadas. Dois cortes rápidos e ouve-se o baque surdo da carne caindo do osso; tendões e ligamentos partem-se como papel molhado. E, apesar de sempre ter tido um gosto pela carnificina, Pudge desenvolveu também, ao longo do tempo, um gosto pelos subprodutos dela. Começando com um bocado de músculo aqui, um trago de sangue ali... e em pouco tempo ele estava fincando profundamente as suas mandíbulas nos torsos mais duros, como um cão que rói trapos. Até aqueles que já não temem o Ceifador, temem este açougueiro.",
        play_style: "O açougueiro pairava sobre o campo, cheio de mortos e moribundos, seu corpo balançando com carne amontoada. Swish, thunk. Pudge corta o tendão da articulação, a carne do osso e devora sua colheita horrenda. Mas as carcaças não substituíram a carne fresca. Então o açougueiro está à espera, olhando através da folhagem com olhos redondos. Era comida ou inimigo? Pudge raramente fazia a distinção. Seu gancho de carne navega pelo ar, arrastando a presa pelo rio com um puxão selvagem. Desorientada, a carne tropeça, engasgando com um cheiro repentino de podridão. Olha para o casco carnudo, esperando por uma resposta, apenas para ver o cutelo cair enquanto o açougueiro desmembra sua próxima refeição em um massacre sangrento."
    },
    {
        name: "Bloodseeker",
        history: "Strygwyr, o Bloodseeker, é um caçador autorizado por ritual, o Cão de Caça dos Gêmeos Esfolados, enviado dos picos enevoados de Xhacatocatl em busca de sangue. Os Esfolados requerem quantidades oceânicas de sangue para se manterem saciados e apaziguados, e em breve sugariam a sua população do seu império montanhoso se os sacerdotes dos elevados planaltos não os satisfizessem. Strygwyr, portanto, vai à procura de carnificina. A energia vital de qualquer sangue que ele derrama flui imediatamente para os Gêmeos através das marcas sagradas nas suas armas e armadura. Ao longo dos anos, ele passou a encorporar a energia de uma fera perversa; em batalha ele é selvagem como um chacal. Por trás da Máscara do Bloodseeker, na afobação de saciamento de sangue, diz-se que por vezes se pode ver os traços dos Esfolados tomando posse direta do seu Cão de Caça.",
        play_style: "A demanda obscena de sangue dos gêmeos esfolados só podia ser atendida através de carnificina constante, tarefa para a qual Strygwyr era mais do que adequado. Impulsionado pela sede insaciável, o Caçador de Sangue sente inimigos feridos de ligas de distância e os persegue com grande velocidade. Através de marcações sagradas em seu equipamento, o sangue dos recém-sacrificados flui diretamente para os Esfolados, deixando apenas o suficiente para curar suas feridas e alimentar sua Fúria Sangrenta. Strygwyr pinta a terra com um anel carmesim, silenciando inimigos apanhados neste Rito de Sangue. Aqueles que correm apenas apressam sua própria morte. O Perseguidor do Sangue rompe todas as artérias, causando uma hemorragia na vítima a cada passo. Pela perda de sangue ou pelas lâminas tribais de Strygwyr, a morte é apenas uma conclusão precipitada."
    },
    {
        name: "Lone Druid",
        history: "Muito antes das primeiras palavras das primeiras histórias surgiu o druídico Clã do Urso. Sábios e justos eles eram, e focados nos seus modos para buscar um entendimento da ordem natural. As antigas forças da natureza viram isso e procuraram o mais culto entre eles. O sábio e velho Sylla, chefe de justiça do clã e vidente, deu um passo à frente pela sua linhagem, e a ele foi dada a Semente com estas palavras: 'Quando tudo no mundo se obscurecer, quando a civilização deixar estas terras, quando o mundo for assassinado e arruinado pelos desertos inacabáveis no fim das eras, plante a Semente'. Agarrando-se à sua confiança, Sylla sentiu os seus anos recuarem e a sua vitalidade retornar. Conhecimento vasto invadiu a sua mente. Ele se descobriu capaz de projetar a sua própria vontade na realidade e, com alguma concentração, alterar a sua própria forma física também. Mas sussurros sutis e ouvidos cruéis levaram o rumor da Semente e do seu poder a outros povos e uma guerra terrível caiu sobre o Clã do Urso. Enquanto o seu lar ancestral queimava, Sylla pegou o seu fardo e fugiu para os territórios selvagens. Eras passaram, e tempo e mito esqueceram-se do Clã do Urso, esqueceram-se de Sylla e a Semente, esqueceram-se de civilizações magníficas que ergueram-se e caíram na vigília do Clã do Urso. Por milênios, Sylla esperou, esperou pela palavra das suas divindades, esperou para que a paz chegasse nos reinos sempre belicosos, esperou em exílio e em segredo pelo fim de todas as coisas e pela conclusão de seu comprometimento sagrado, preparando-se sempre para encarar e destruir qualquer coisa que ousar ameaçar o seu propósito.",
        play_style: "Escolhido pelas forças da natureza por sua profunda sabedoria, Sylla é tudo o que resta de seu clã esquecido. O Druida Solitário é seguido por seu Urso Espiritual, um poderoso companheiro que enreda inimigos e destrói estruturas. O som de um Savage Roar geralmente é tudo o que é necessário para assustar os inimigos da floresta. Caso contrário, o par entra em um estado raivoso, aumentando sua velocidade à medida que percorrem as terras em busca de intrusos. Homem ou urso, a distinção nem sempre é clara. Quando a situação exige, o Lone Druid toma sua Forma Verdadeira, solta um grito de guerra revigorante e se junta ao mêlée para lutar lado a lado com seu urso."
    },
    {
        name: "Razor",
        history: "Dentre os poderes emblemáticos que populam o Escapo Inferior, Razor, o Lightning Revenant, é um dos mais temidos. Com o seu chicote eletrocutante, ele patrulha o Labirinto Estreito, a teia traiçoeira de passagens pela qual as almas dos mortos são sorteadas de acordo com a sua inteligência, astúcia e persistência inatas. Deslizando por cima do Labirinto, Razor olha para as almas perplexas por baixo dele e distribui choques de eletricidade escaldante que tanto castigam e apressam as almas enquanto elas decidem os seus próprios destinos, correndo para saídas luminosas ou para covas escuras sem fim. Razor é a personificação eterna de um poder dominante, abstrato e quase clínico na sua aplicação do poder. No entanto, ele tem um ar altivo que sugere uma satisfação sarcástica no seu trabalho.",
        play_style: "O chicote que introduz os mortos através do labirinto estreito traz tanta dor no campo de batalha. O Revenant de Raios irradia um Campo de Plasma que choca os inimigos próximos, uma vez na expansão e outra vez na contração. Ele se conecta aos heróis inimigos com um link estático, transferindo seu poder para suas próprias reservas. Carregado com uma corrente instável, Navalha paira sem esforço do chão e envia solavancos de eletricidade para aqueles que ousam chegar perto demais. No Olho da Tempestade, encontra-se Navalha, observando e deliciando-se com seu trabalho, enquanto raios reduzem seus inimigos a restos carbonizados."
    },
    {
        name: "Vengeful Spirit",
        history: "Até o mais satisfeito Skywrath é uma criatura mal-humorada, naturalmente propensa a se vingar pelo mais ínfimo dos insultos. Mas a Vengeful Spirit é a essência da vingança. Outrora uma orgulhosa e feroz descendente dos Skywrath, Shendelzare era a primeira na sucessão do Ninho de Águia Fantasma até que a traição de uma irmã roubou-a do seu direito de nascença. Presa na teia de um assassino, Shendelzare somente libertou-se ao custo das suas asas, mancando para longe na mais derradeira das humilhações: a pé. Com as suas asas quebradas, ela sabia que os Skywrath nunca a aceitariam como governante; e no mais alto poleiro do Ninho, inacessível exceto para a revoada alada, a sua irmã era intocável. Recusando-se a viver como uma aleijada sem asas e desejando vingança acima de qualquer poder terreno, a princesa caída fez um acordo com a deusa Scree'auk: ela trocou o seu corpo arruinado por uma forma imortal de energia espiritual, impulsionada pela vingança, capaz de causar grande estrago no plano material. Ela pode até passar a eternidade sem voar, mas terá a sua vingança.",
        play_style: "Roubada suas asas e de seu lugar de direito no Ninho de Águia Fantasma, Shendelzare recorreu à deusa Scree'auk para fornece-lá energias sombrias, que executariam sua vingança. A princesa caída anuncia sua chegada com uma Onda Aterrorizante, desalentando os inimigos pertos o suficiente para ouvir seu grito angustiado. Como seus irmãos aéricos, a Vengeful Spirit faz uso franco do Míssil Mágico, uma habilidade simples dos Skywrath para atordoar os adversários. Em busca do martírio, Shendelzare imediatamente faz uma Troca das Profundezas com um herói da sua escolha, sacrificando-se de bom grado, enquanto troca de posição com um aliado cercado ou um inimigo fugitivo. O digno, que luta ao lado da Shendelzare, é encorajado pela Aura da Vingança, um fanatismo que intensifica seu ataque e que continua após a sua morte."
    },
    {
        name: "Enigma",
        history: "Nada se sabe sobre o passado do Enigma. Existem apenas histórias e lendas, a maioria delas apócrifas, passadas através das eras. Na verdade, o Enigma é um mistério cuja única biografia verdadeira é a descrição: ele é uma força universal, um consumidor de mundos. Ele é um ser do vazio, às vezes corpóreo, outras vezes etéreo. Uma besta entre os planos. Há histórias que dizem que ele era um grande alquimista que tentou desvendar os segredos do universo e acabou sendo amaldiçoado pela sua arrogância. Outras lendas dizem que ele é um ser antigo de gravidade estranha, o abismo personificado – uma voz distorcida de fora da escuridão original, anterior à primeira luz do universo. E há lendas mais antigas que dizem que ele é a primeira estrela que desabou, um buraco negro que se tornou complexo e consciente – as suas motivações incompreensíveis, o seu poder inexorável, uma força de destruição desencadeada sobre a existência em si.",
        play_style: "Um mistério digno de seu nome, Enigma só poderia ser descrito como um ser do vazio, um animal entre os aviões. Ele desenha aspectos de si mesmo de outras dimensões, realizando Conversões Demoníacas para convocar numerosos Eidolons. O chão escurece sob um pulso da meia-noite, e os inimigos ficam atordoados pela força invisível de Malefice, enquanto tentam fugir de seus efeitos entrópicos. Uma lenda diz que Enigma é realmente a primeira estrela em colapso. Essa teoria se torna mais plausível quando o Enigma começa a canalizar uma singularidade cósmica, puxando todos, exceto a si mesmo, para o centro superdenso de seu Buraco Negro."
    },
    {
        name: "Lich",
        history: "Durante a vida, o mago congelado Ethreain (ainda não era um Lich) tinha usado a ameaça de gelo destrutivo para escravizar reinos inteiros. Os seus súditos, ajudados por alguns mágicos desesperados, ganharam a coragem suficiente para o emboscarem. Armados com a quantidade de corda encantada suficiente para o prenderem para sempre, amarraram o mago congelado a pesos de diamante e atiraram-no para uma lagoa que se pensava não ter fundo. Mas afinal tinha. Ele apenas caiu durante mais ou menos um ano antes de um afloramento o ter agarrado. Aí ficou, morto mas sem se decompor, até que o geomante Anhil considerou verificar a lenda da suposta Lagoa Negra sem fundo. O fio de prumo de Anhil entrelaçou-se com as cordas que prenderam o feiticeiro afogado e arrastou para cima um prêmio inesperado. Pensando então que tornando o morto um morto-vivo pudesse questioná-lo sobre as propriedades da lagoa, este remove as cordas e começou um ritual simples de ressurreição. Até os descendentes dos inimigos de Ethreain estavam bem esquecidos pelo tempo, portanto não havia ninguém para avisar Anhil contra esta imprudência. Mas ele aprendeu quase instantaneamente o erro do seu juízo, assim que Lich retirou as algemas e o consumiu.",
        play_style: "Ressuscitado por um geomante curioso, Ethreain retirou suas algemas, e fez imediatamente um Sacrifício com seu salvador por mana. Finalmente libertado das profundezas da Lagoa Negra, o Lich retorna para causar uma destruição glacial no mundo. Protegendo seus seguidores com Escudo Congelado, Ethreain flutua sobre o campo de batalha para causar uma Explosão Congelante em qualquer um que cruze seu caminho. Uma esfera congelada desce sobre seus inimigos, passando de um corpo para o próximo, até o Congelamento em Cadeia persuadir toda a oposição a ficarem de joelhos."
    },
    {
        name: "Oracle",
        history: "Os ascendentes do Grande Trono de Cymurri têm trazido por eras os seus Oráculos exclusivamente do Incubatório de Marfim, no topo dos "+
        "picos ocos da Faixa do Zelota, com o pagamento inicial feito na concepção do embrião e a liquidação do débito na entrega de um profeta maduro e "+
        "bem treinado para o Portão do Rei Esculpido. Criados pelas Sibilas Pálidas que os procriaram e deram à luz, todos os Oráculos sancionados eram "+
        "ancorados pelas suas formas físicas ao mundo que a maior parte dos seres vivos hoje compartilha; enquanto isso, as suas almas vagueavam muito "+
        "distantes, quase desligadas pelo mais leve cordão umbilical astral. Os profetas retornariam desses vagueios cósmicos, dizendo palavras de fogo "+
        "com línguas de carne. As suas dicções místicas eram analisadas pelos Conselheiros de Cymurri, que encontravam nelas visões do futuro, conselhos "+
        "diplomáticos, toda a munição sobrenatural necessária pela árvore genealógica dos Reis Esculpidos necessária para garantir a vitória em todas as "+
        "campanhas, seja num tribunal ou em um campo de batalha.Portanto por gerações, as páginas do Tomo Esculpido vinham repletas de nomes de reis "+
        "triunfantes e os novos domínios que haviam conquistado.Assim o foi, isto é, até um certo Oráculo chamado Nerif chegar para servir ao último "+
        "rei de elmo de pedra. As profecias de Nerif desde o início eram incomuns. Elas não pareciam meramente prever o futuro, mas sim moldá- lo. O "+
        "estranho adivinho soltava conselhos que ninguém havia pedido e do nada os Cymurri se encontravam mergulhados em conflitos com inimigos recém - "+
        "descobertos. Os Conselheiros, sentindo o seu poder sendo ameaçado, rapidamente culparam o último Oráculo por tais indesejados acontecimentos. "+
        "Eles exigiam a sua remoção, peticionando às Sibilas que recuperassem o seu profeta defeituoso e o substituíssem com um substituto de valor. "+
        "Mas Nerif descreveu um mau - agouro da destruição do Incubatório e, horas depois, chegaram notícias da destruição da antiga escola por uma "+
        "avalanche catastrófica. Temendo o mesmo destino das Sibilas Pálidas, os Conselheiros voltaram aos seus aposentos, agora evitando ao máximo "+
        "serem percebidos pelo Oráculo. O Rei Esculpido, porém, era dotado de grande praticidade. Ele duvidou da dedicação dos seus Conselheiros "+
        "hiperprudentes. Um Oráculo de tamanha raridade, ele argumentou, deveria ser usado como uma arma para aumentar o seu domínio. Portanto, "+
        "ele rebaixou os seus conselheiros tímidos e colocou Nerif ao seu lado. Com apenas um entendimento raso do talento de Nerif, ele audaciosamente "+
        "declarou os resultados que desejava e persuadiu Nerif a proferir os seus desejos como profecia. No início, tudo estava bem.O último Rei "+
        "Esculpido se gabava de que, ao adotar o animal de estimação do Destino, ele o havia transformado em um mero brinquedo. Ele então deveria ter "+
        "ficado alerta quando, na véspera da invasão que fez no reino da Sátrapa Inquietável, tentou arrancar uma previsão de vitória certa do seu "+
        "Oráculo para apenas ouvir Nerif sussurrar baixo 'A vitória pode ser de qualquer um'. Ele não poderia conseguir uma afirmação mais concreta "+
        "dos lábios de Nerif. Mesmo assim, o Rei tinha confiança no seu exército. A Sátrapa estava sitiada, mal armada e afastada de quaisquer aliados "+
        "possíveis. Ele considerou que 'A vitória pode ser de qualquer um' indicava que, com um poderio tático ao lado, o seu plano dificilmente "+
        "falharia. É claro que já sabemos que ele deveria ter levado as palavras do interlocutor de forma mais literal.Mesmo com um estudo cuidadoso "+
        "dos Anais Anotados do Se, o que ocorreu no campo de batalha do palácio da Sátrapa Inquietável é quase impossível de ser visualizado. "+
        "Aparentemente, no meio da carnificina, o confronto começou a se bifurcar.A cada momento - chave, a realidade se rachava e se quebrava em "+
        "pedaços. Soldados que cambaleavam e morriam na batalha também se mantinham em pé, avançando à luta. As suas mentes também se dividiram; "+
        "os guerreiros se encontravam ao mesmo tempo vivos e mortos, existentes e não existentes. A vitória e a derrota estavam particionadas, de "+
        "forma que cada resultado separado era sentido simultaneamente pelos dois exércitos. O universo se tornou um salão de espelhos, com todos "+
        "eles se quebrando sem parar.O efeito imediato em ambos foi a insanidade. Incapaz de compreender o estado de ser tanto triunfante quanto "+
        "derrotado, a mente do Rei Esculpido se dissipou em partículas de loucura. A ingênua Sátrapa não teve um destino melhor. As realidades opostas "+
        "combinadas continuavam a se dividir mais e mais, ecoando em histórias infinitas, todas elas populadas por multidões desnorteadas que em breve "+
        "perderam as habilidades de se alimentar, vestir, defender ou reproduzir da maneira tradicional. Porém, muito antes destas repercussões "+
        "agirem, os Conselheiros de Cymurri, cautelosos, capturaram Nerif, o amarraram, amordaçaram e lançaram para longe do universo deles a uma "+
        "velocidade muito alta em uma barca dimensional, esperando que ele fosse a um lugar onde não poderia lhes causar mais mal. Mas é claro que "+
        "era tarde demais para eles. E pode sê - lo também para nós.",
        play_style: "Designadas para conciliar o Rei Graven, as palavras de Nerif se tornaram realidade com tanta precisão que seus conselheiros começaram a questionar se o Oráculo apenas falava profecias ou moldava os próprios caminhos do próprio destino. Exilado de seu próprio universo por seus poderes perturbadores, Nerif agora transforma seus dons em preocupações mais imediatas. Poderia ir de qualquer jeito. As famosas palavras do Oráculo refletem suas próprias ações de dois gumes. Purgando bênçãos e maldições, o Fim da Fortuna chega mais cedo do que o esperado. O decreto do destino protege os heróis da magia, mas os impede de levantar os braços. Chamas Purificadoras estimulam a regeneração, mas não sem as dores iniciais da limpeza. Os aliados podem se encontrar brevemente imunes à cura e ao dano, apenas para receber seus efeitos duplos no final da Falsa Promessa de Nerif."
    },
    {
        name: "Rubick",
        history: "Qualquer mago pode lançar um ou dois feitiços e talvez alguns estudem por tempo o suficiente para se tornar um feiticeiro, mas apenas os mais talentosos podem ser reconhecidos como um Magus. No entanto, em todo círculo de feiticeiros um senso de comunidade nunca foi garantia de cortesia entre competidores. Já sendo um duelista renomado e um estudioso do majestoso mundo da feitiçaria, nunca ocorreu a Rubick que ele tivesse o potencial de ser um Magus, pelo menos até sofrer a sétima tentativa de assassinato. Enquanto ele casualmente atirava de uma sacada o décimo segundo aspirante a assassino, ele percebeu a falta de criatividade nas suas últimas tentativas de assassinato. Se antes um mero estalar de dedos ou uma bola de fogo poderia tê-lo feito saltar alegremente, agora tudo havia se tornado tão previsível. Ele ansiava por mais competição. Ao colocar a sua máscara de combate, ele fez o que qualquer feiticeiro buscando ascender níveis faria: ele anunciou a sua intenção de matar um Magus. Rubick rapidamente descobriu que ameaçar um Magus é ameaçar todos os Magus, e eles investiram contra ele em massa. Cada feitiço dos seus oponentes era uma torrente de energia e cada ataque um golpe mortal certo. Mas logo ocorreu algo inesperado para os adversários de Rubick: as suas técnicas pareciam se voltar contra eles. No interior do redemoinho de magia, Rubick gargalhava, sutilmente prevendo e replicando os poderes de um e lançando-o contra outro, semeando caos entre aqueles que tinham se aliado contra ele. Acusações de traição começaram a se espalhar e logo os feiticeiros se viraram contra si próprios sem suspeitar quem estava por atrás da sua discórdia. Quando a batalha chegou ao seu desfecho, todos estavam chamuscados e congelados, ensopados, cortados e perfurados; muitos se encontravam mortos por ataques aliados. Rubick se manteve afastado, machucado mas encantado pelas festividades da semana. Nenhum deles teve coragem suficiente para contestar quando ele apresentou a sua petição ao Conselho Oculto, e então os Onze Imateriais concordaram por unanimidade em concedê-lo o título de Grande Mago.",
        play_style: "Um renomado duelista entre feiticeiros, Rubick ascendeu ao título de Grande Mago através da cuidadosa eliminação de seus rivais. Acostumado a assassinos, Rubick reage levantando os atacantes do chão e os joga pela sala com Telecinesia. As energias arcanas são atenuadas por seu Campo Nulo, enquanto os braços convencionais vacilam após serem atingidos com Fade Bolt. Nenhuma mágica está além do alcance do Grande Mago. Rubick replica especialidades inimigas com Spell Steal, decifrando seus segredos antes de devolvê-los aos seus donos."
    }
];

const btn_hero = document.querySelectorAll(".btn_hero");
var a;
var b;

btn_hero.forEach(element => {
    element.addEventListener('click', () => {
        a = element.innerHTML;
        b = hero.find(element => element.name == a);

        document.getElementById("hero_name").innerText = b.name;
        document.getElementById("p_history").innerText = b.history;
        document.getElementById("p_play_style").innerText = b.play_style;
        document.getElementById("h2_play_style").style.visibility="visible";
        document.getElementById("h2_history").style.visibility="visible";
        element.style.backgroundColor="rgb(148, 28, 28)";
        element.style.color="white";

        for(var i=0; i<document.getElementsByClassName("btn_hero").length;i++) {
            if(element.innerHTML != document.getElementsByClassName("btn_hero")[i].innerHTML) {
                document.getElementsByClassName("btn_hero")[i].style.backgroundColor="white";
                document.getElementsByClassName("btn_hero")[i].style.color="black";
            }
      }
    })
});

btn_hero.forEach(element => {
    element.addEventListener('keydown', (e) => {
        if(e.which == 9)
        {
            e.returnValue=false;
        }
        
    })
})